package com.um.biblioteca.exception;

import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.ControllerAdvice;
import org.springframework.web.bind.annotation.ExceptionHandler;
import org.springframework.web.context.request.WebRequest;

@ControllerAdvice
public class GlobalExceptionHandler {

    @ExceptionHandler(BibliotecaException.class)
    public ResponseEntity<ApiError> handleBibliotecaException(BibliotecaException ex, WebRequest request) {
        ApiError apiError = new ApiError(
            ex.getStatus(),
            HttpStatus.valueOf(ex.getStatus()).getReasonPhrase(),
            ex.getMessage(),
            request.getDescription(false)
        );
        return new ResponseEntity<>(apiError, HttpStatus.valueOf(ex.getStatus()));
    }
    
    @ExceptionHandler(LibroNoEncontradoException.class)
    public ResponseEntity<ApiError> handleLibroNoEncontradoException(LibroNoEncontradoException ex, WebRequest request) {
        ApiError apiError = new ApiError(
            404,
            HttpStatus.NOT_FOUND.getReasonPhrase(),
            ex.getMessage(),
            request.getDescription(false)
        );
        return new ResponseEntity<>(apiError, HttpStatus.NOT_FOUND);
    }
    
    @ExceptionHandler(UsuarioNoEncontradoException.class)
    public ResponseEntity<ApiError> handleUsuarioNoEncontradoException(UsuarioNoEncontradoException ex, WebRequest request) {
        ApiError apiError = new ApiError(
            404,
            HttpStatus.NOT_FOUND.getReasonPhrase(),
            ex.getMessage(),
            request.getDescription(false)
        );
        return new ResponseEntity<>(apiError, HttpStatus.NOT_FOUND);
    }
    
    @ExceptionHandler(PrestamoNoEncontradoException.class)
    public ResponseEntity<ApiError> handlePrestamoNoEncontradoException(PrestamoNoEncontradoException ex, WebRequest request) {
        ApiError apiError = new ApiError(
            404,
            HttpStatus.NOT_FOUND.getReasonPhrase(),
            ex.getMessage(),
            request.getDescription(false)
        );
        return new ResponseEntity<>(apiError, HttpStatus.NOT_FOUND);
    }
    
    @ExceptionHandler(RecursoNoDisponibleException.class)
    public ResponseEntity<ApiError> handleRecursoNoDisponibleException(RecursoNoDisponibleException ex, WebRequest request) {
        ApiError apiError = new ApiError(
            409,
            HttpStatus.CONFLICT.getReasonPhrase(),
            ex.getMessage(),
            request.getDescription(false)
        );
        return new ResponseEntity<>(apiError, HttpStatus.CONFLICT);
    }
    
    @ExceptionHandler(DatosInvalidosException.class)
    public ResponseEntity<ApiError> handleDatosInvalidosException(DatosInvalidosException ex, WebRequest request) {
        ApiError apiError = new ApiError(
            400,
            HttpStatus.BAD_REQUEST.getReasonPhrase(),
            ex.getMessage(),
            request.getDescription(false)
        );
        return new ResponseEntity<>(apiError, HttpStatus.BAD_REQUEST);
    }
    
    @ExceptionHandler(Exception.class)
    public ResponseEntity<ApiError> handleGlobalException(Exception ex, WebRequest request) {
        ApiError apiError = new ApiError(
            500,
            HttpStatus.INTERNAL_SERVER_ERROR.getReasonPhrase(),
            "Ocurri√≥ un error inesperado: " + ex.getMessage(),
            request.getDescription(false)
        );
        return new ResponseEntity<>(apiError, HttpStatus.INTERNAL_SERVER_ERROR);
    }
} 